### ISSUE TITLE
Add Workman Keyboard Layout

### ISSUE THREAD

**Issue by TheBlueOompaLoompa** [futo-org/futo-keyboard-layouts#50] opened 2024-07-04 06:44 UTC
I use the workman layout on my computer, but I haven't been able to find a good keyboard that actually supports workman on mobile. It would be awesome if this supported it.

**Comment by dean-futo** [comment] 2024-11-24 03:42
Closing as duplicate of #13

**Closed by dean-futo** 2024-11-24 03:42 UTC
Labels: Low Priority, Medium Complexity
